### ISSUE TITLE
[Question] gd-ecs and godex?

### ISSUE THREAD

**Issue by farfalk** [Jonchun/gd-ecs#2]
First of all, I love your approach. I will try to implement it in my project and start contributing asap - in one or two months, I hope.

Coming to the question: Recently, this other ecs-for-godot library has been published on github: [Godex](https://github.com/AndreaCatania/godex) by the developer [AndreaCatania](https://github.com/AndreaCatania/).

As far as I can understand, it goes for a much more "pure" approach, implementing a system-component-entity control loop that completely supersedes the standard oop-like godot approach. What are your opinions on that? Do you think it's possible to bridge your efforts and his in a sort of comprehensive hybrid/pure general ecs framework like the one in unity?

What I love of your approach is that it doesn't "throw away" the scene tree and the default node types like godex seems to do. At the same time, Godex seems to be much more low level and integrated with the engine.

Thanks again for sharing, hope to contribute soon!

**Comment by SSebigo** [comment]
Is this project dead? Seems like even the simple merge requests are waiting for some time now.

**Comment by jonchun** [comment]
Sorry that I've been quite inactive for a while. Life happened and I temporarily lost motivation/interest in Github related things.  I've peeked at Godex before, but as you mentioned, it seems like it is a full shift away from Godot's nodes and over to a strict ECS. This is probably "better" in many ways and there's obviously much more code/effort that went into that project than I put into this one. When I initially started this project, I was playing around with ECS as a paradigm rather than for performance reasons or whatnot.

I'm not quite sure there is very much value in merging the efforts here since the directions are extremely different. My project here is a "quick and dirty" (and also my first) attempt at organizing gdscript into an ECS structure, while also staying true to the original Godot nodes and meant more of an organizational guideline and to help with decoupling of code vs a true ECS architecture.

I'm definitely open to fixing up/adding features or perhaps even rewriting parts of the code to not use GDscript if performance becomes an issue, but I'm not sure if that's really going to be a problem unless someone starts a major project with this (which is unlikely)

I'm going to close this issue because I don't think there's really much action to be taken here, but please do feel free to re-open if there are  follow up questions or suggestions that might change my mind.
